# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placebet',
            name='prediction',
            field=models.BooleanField(default=True),
        ),
    ]
